### ISSUE TITLE
Syskit Shell not working with websocket 1.2.3

### ISSUE THREAD

**Issue by 2maz** [rock-core/tools-syskit#101]
Syskit shell is not opening when using websocket 1.2.3 - using 1.2.2 is doing fine though.

**Comment by doudou** [comment]
I'm running just fine on 1.2.3. Any more info ? (backtrace, ...)

**Comment by doudou** [comment]
Ruby version would be useful too.

**Comment by 2maz** [comment]
Ubuntu 14.04/ruby2.0 -- syskit shell sits in the while loop of  Roby::Interface::DRobyChannel.read_packet

What is to be observed when syskit shell is opened:
syskit run --> with websocket 1.2.2: calls Roby::Interface::DRobyChannel.read_packet and then continues with calls to Roby::Interface::DRobyChannel.write_packet -- with websocket 1.2.3 this does not happen

**Comment by doudou** [comment]
Was a 2.0-specific error, I don't plan to investigate it further. 1.2.4 works like a charm on Ruby 2.1+
