### ISSUE TITLE
ide: job exceptions are not always shown

### ISSUE THREAD

**Issue by doudou** [rock-core/tools-syskit#146]
There are cases where exceptions during job execution are not shown within the IDE. One has to go back to the console to find them.

So far, no precise pattern. We should document each specific case here to try reproducing and fixing them.

**Comment by g-arjones** [comment]
I know that you basically open this issues as notes to self but if you added a quick description and steps to reproduce maybe you could receive patches from contributors willing to help :)

**Comment by doudou** [comment]
I've fixed the ones I and Gabriel could regularly hit (https://github.com/rock-core/tools-roby/pull/102, https://github.com/rock-core/tools-roby/pull/95). I'd like to be optimistic, and am closing this issue. Let's reopen if we start seeing more ...
