### ISSUE TITLE
ruby 2.0.0p457 (2014-03-03) [x86_64-linux-gnu]: syskit shell hangs for 8minutes by entering invalid commands

### ISSUE THREAD

**Issue by goldhoorn** [rock-core/tools-syskit#25]
The Syskit shell hangs for ~8minutes if a wrong command is types
syskit/roby on debug level does not give extra information.

After the 8 minutes everything is working fine.

(p.s. we switched to 1.9.1 everything is fine for us currently)

**Comment by goldhoorn** [comment]
@doudou this is still valid :-(

**Comment by doudou** [comment]
This is probably a problem with 2.0+ calling #inspect to build exception messages (instead of #to_s in 1.9). #inspect can be horribly expensive.

Do not ask me why in hell they did that.

**Comment by doudou** [comment]
This should be fixed nowadays. Roby overloads #inspect to redirect to #to_s for by default for all objects.
