### ISSUE TITLE
add_optional causes unexpected behaviours

### ISSUE THREAD

**Issue by goldhoorn** [rock-core/tools-syskit#34]
On compositon level:
If a component got stopped (by normal system operation) the whole composition is failing.
We could not find a way to block the signal forwarding in this case.

The source was:
Composition A used optional component O, which was not added automatically
If Compositon B got started which used O, O is added to A by the netowrk-resolution (which not make sense in any case.... this is related to #23)
If B got stopped, O got stopped to
The stopping of O causes A to fail

**Comment by doudou** [comment]
Re-reading this, and now finally spending some time running stuff on Roby, my guess is that one was forcefully killing "O", which under the generated network has to cause the failure of B. If you don't want it to, specify it at the dependency level. Out of the top of my head it would look like:

~~~
  # We really don't care what happens to this child
  add(ChildModel, success: nil, failure: nil)
~~~


Moreover, until I get a proper data stream proving to me that syskit was in error here (i.e. that the generated network was erroneous under the constraints), I'm closing this. Note that the functionality of explicitely deselecting an optional child is now in master (https://github.com/rock-core/tools-syskit/pull/72)
