### ISSUE TITLE
ide: don't show some types

### ISSUE THREAD

**Issue by gustavoneves12** [rock-core/tools-syskit#65]
I couldn't to find Base::PoseSrv when I execute syskit ide command.

**Comment by doudou** [comment]
Base::PoseSrv is a deprecated naming (I guess you got the name from the tutorials, which are unfortunately outdated). It now aliases to Rock::Services::Pose

In other words, there's no service called "Base::PoseSrv", but you can use Base::PoseSrv in the syskit models, it should "simply" be an alias to Rock::Services::Pose. This aliasing cannot be shown by syskit ide, really (well, it could, but given that it's useful mainly in transitions I personally see it mostly as a enhancement and not a bug).

**Comment by doudou** [comment]
Opened #66 to keep track of the functionality, closing this now.
