### ISSUE TITLE
Deployment: waits unlimited time until process is running

### ISSUE THREAD

**Issue by D-Alex** [rock-core/tools-syskit#92]
In the case of a gazebo deployment it is expected that someone is manually starting the gazebo process. Until then, syskit happily waits without giving any feedback polling wait_running on the gazebo world. I would assume this is also a problem for starting real deployments which might freeze for whatever reason.

Therefore, I miss a default timeout which triggers a failure after n seconds (Syskit.conf.timeouts.deployment.start = 30 #seconds?). In the case of gazebo I am adding a warning in the World::wait_running method.

     gazebo_world_xxxx: Waiting for Gazebo server. You have to start the simulation via "rock-gzserver WORLDFILE"

**Comment by doudou** [comment]
Deployments must wait forever. They do not block Syskit itself, so if you want some form of timing out / message to the user, the best is to implement it in the Syskit support for rock-gazebo.
