### ISSUE TITLE
Generating a Composition Error

### ISSUE THREAD

**Issue by rafaelsaback** [rock-core/tools-syskit#96]
I was generating a new composition, but for some reason syskit was disconsidering a " _ " character of the name I used (check the image below). This has happened with different names, but basically only when I had " _ " + character + " _ " OR had " _ " + character + character + " _ ".

So I had to correct the files by hand later.

![sys_gen_cmp_bug](https://cloud.githubusercontent.com/assets/7912190/13189031/d938cf4a-d733-11e5-810f-ba0bb4c1a6df.png)

**Comment by doudou** [comment]
Workaround: pass the target class name instead of the file name (ModelPredictiveControl/ConstantAlignedVelZControl) which should have worked. (Disclaimer: not tested).

**Comment by rafaelsaback** [comment]
Using the following command:

```
syskit gen cmp ModelPredictiveControl/ConstantAlignedVelZControl
```

Generates, for example, the following folder:

```
models/compositions/model_predictive_control/constantalignedvelzcontrol.rb
```

Am I missing something?

**Comment by doudou** [comment]
`syskit gen` in master stopped trying to guess between models and files. The argument is now always a file name from which the class name is inferred.
